title: "Sankalp Chudmunge"
description: "Physics Grad | Backend Engineer | Computational Physicist"
author: "Sankalp Chudmunge"
email: "csankalp21@gmail.com"
phone: "+91 8766775227, +91 9082586324"
github_username: "mountain-snatcher"
baseurl: ""
url: "https://mountain-snatcher.github.io"
theme: jekyll-theme-minimal
show_downloads: false