services:
  - type: web
    name: github-page-sankalp
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    healthCheckPath: /health